version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: prueba_tecnica_todo
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prueba"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: django_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=prueba_tecnica_todo
      - DB_USER=prueba
      - DB_PASSWORD=prueba
      - DB_HOST=db
      - DB_PORT=5432
      - GEMINI_API_KEY=AIzaSyD_t6C77k_whci_qUsvEvfg0npCiczdxek
      - GEMINI_MODEL=gemini-2.5-flash
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
